# Generated by Django 2.1.1 on 2020-05-05 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=200)),
                ('league', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=50)),
                ('typeline', models.CharField(max_length=50)),
                ('ilvl', models.IntegerField(default=0)),
                ('note', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('I', 'Implicit'), ('E', 'Explicit'), ('C', 'Crafted')], default='E', max_length=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itemviewer.Item')),
            ],
        ),
        migrations.AddField(
            model_name='categories',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itemviewer.Item'),
        ),
    ]
