# Generated by Django 2.1.1 on 2020-05-05 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemviewer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='mod',
            field=models.CharField(max_length=300),
        ),
    ]
